### ISSUE TITLE
Add more programming language

### ISSUE THREAD

**Issue by kmrakash** [kmrakash/HELLO_WORLD#11]
Find the list of most of the programming language from [https://en.wikipedia.org/wiki/List_of_programming_languages](https://en.wikipedia.org/wiki/List_of_programming_languages)

- Create a issue for the same 
- create a pull request

**Comment by kushaangowda** [comment]
I have already added HELLO WORLD code in C, ccan i add it in Ruby too??

**Comment by Utpal29** [comment]
#27 added R

**Comment by Chawklate** [comment]
Can i add Hello World Javascript but with different method?

**Comment by kmrakash** [comment]
@Chawklate  yeah sure please go ahead
