### ISSUE TITLE
C 

### ISSUE THREAD

**Issue by kmrakash** [kmrakash/HELLO_WORLD#2]
Follow contribution guide and write a hello world programme in C

**Comment by SidBthegr8** [comment]
Can do this. Please assign.

**Comment by kmrakash** [comment]
Please complete one PR at a time . I should give oppurtunity to everyone

**Comment by instareasy** [comment]
Kindly assign this to me. I can do this one.

**Comment by kushaangowda** [comment]
Hi @kmrakash, I have a new PR for hello world in C
