### ISSUE TITLE
Simplify workflow when adding a new language

### ISSUE THREAD

**Issue by reverk** [kmrakash/HELLO_WORLD#41]
Hi @kmrakash, as mentioned in #9, I wanted to make an improvement when adding a new language.

Currently, users have to copy the given HTML code and paste it in. Then fill in the necessary data. 

With ListJs, it's possible to simplify to: 
```
let data = [
    {
        'lang': "Java",                                 // Data-Lang attribute
        'lang-name': "Java",                            // Language name
        'lang-image': "./images/java.png",              // Language image
        'contributor': "John Doe",                      // Github Contributor (name)
        'contributor-link': "https://www.github.com",   // Github Contributor (link)
    },
    // And more data
];
```

... and let it loop itself instead of copy-pasting it.

However, to keep the code readable, existing languages will need to move it to the data file. 

What do you think?

**Comment by kmrakash** [comment]
If you can do so , please make all necessary changes
